---
format:
  pdf:
    tbl-cap-location: top
    dpi: 500
    fig-pos: "H"
    number-sections: true
    cite-method: natbib
    include-in-header: 
      - text: |
          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
          \usepackage{rotating}
          \newcommand{\bsideways}{\begin{sidewaystable}[htbp]}
          \newcommand{\esideways}{\end{sidewaystable}}
      - file: preamble.tex 
    include-before-body: title.tex
    keep-tex: TRUE
    fig-format: png
    default-image-extension: png
  docx:
    reference-doc: new_template_no_numbering.docx
pdf-engine: lualatex
# monofont: "DejaVu Sans Mono"
# mainfont: "Times New Roman"
execute: 
  echo: false
  warning: false
editor: source
bibliography: references.bib
biblio-style: apalike
natbiboptions: round
link-citations: true
linkcolor: blue!000!black
urlcolor: blue!000!black
citecolor: blue!000!black
linestretch: 1.5
indent: TRUE
title-block-banner: false
title-block-style: none
---


```{r setup}
#| include=FALSE
options(scipen=999)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      dpi = 500, 
                      fig.pos = "H", 
                      fig.env= 'figure', 
                      tab.topcaption = TRUE,
                      ft.align = "left",
                      ft.arraystretch = 0.5
                      )
library(tidyverse)
library(readr)
library(readxl)
library(zoo)
library(magick)
library(stringi)
library(patchwork)
library(xtable)
library(scales)
library(rvest)
library(rebus)
library(PNWColors)
library(lubridate)
library(here)
library(flextable)
library(gt)
library(officer)
library(officedown)
library(modelsummary)
library(sandwich)
library(lmtest)

set_flextable_defaults(
  font.size = 7,
  digits = 2,
  font.family = "Arial",
  border.color = "black",
  border.width = 0.5,
  fp_border = fp_border(color = "black", width = 0.5, style = "solid")
)


```

```{r functions}
source(here("Functions","flextable_word.R" ))
source(here("Functions","modelsummary_word.R" ))
source(here("Functions","modelplot_word.R" ))
source(here("Functions","borderlines.R" ))
```

```{r}
sa_news_models_tbl <- 
  read_rds(here("Outputs", "artifacts_sa_news_models.rds")) |> 
  pluck(1)
sa_resids_models_tbl <- 
  read_rds(here("Outputs", "artifacts_sa_residual_models.rds")) |> 
  pluck(2)
us_news_models <- 
  read_rds(here("Outputs", "artifacts_us_news_models.rds"))
us_resids_models <- 
  read_rds(here("Outputs", "artifacts_us_residual_models.rds"))

interest_rate_diff_models <- 
  read_rds(here("Outputs", "artifacts_differntial_models.rds"))


```




# Introduction

@fornero2011effect 

# Literature review

# Data and methodology

# Results


```{r}

pretty_table <- function(tbl, surprise = "target_models", surprise_exist = 1, label = NULL) {
  
  result <- tbl
  
  if (surprise_exist == 1) {
    result <- result |> filter(surprise_type == surprise)
  }
  
  result <- result |>
    rename(any_of(c(model = "predictor_model"))) |>
    filter(term != "(Intercept)") |>
    select(model, term, estimate, std.error, p.value) |>
    mutate(
      stars     = ifelse(p.value < 0.01, "***",
                  ifelse(p.value < 0.05, "**",
                  ifelse(p.value < 0.1,  "*", ""))),
      estimate  = round(estimate,  4),
      std.error = round(std.error, 4)
    ) |>
    mutate(estimate = paste0(estimate, stars, "\n(", std.error, ")")) |>
    select(-p.value, -stars, -std.error)
  
  if (!is.null(label)) result <- result |> mutate(source = label, .before = 1)
  
  result
}

combined_table <- function(surprise = "target_models") {
  
  # Pre-process decomposed table: split predictable/unpredictable into
  # separate source labels so each model has one row per source
  decomposed <- interest_rate_diff_models |> 
    pluck(1) |> 
    pretty_table(surprise = surprise)
  
  sa_news <- sa_news_models_tbl |> 
    pretty_table(surprise = surprise, label = "SA News") |>
    pivot_wider(id_cols = model, names_from = source, values_from = estimate)

  sa_resids <- sa_resids_models_tbl |>
    pretty_table(surprise = surprise, label = "SA Residuals") |>
    pivot_wider(id_cols = model, names_from = source, values_from = estimate)

  main <- bind_rows(
    decomposed |> filter(term == "unpredictable") |> mutate(source = "SA Residuals"),
    decomposed |> filter(term == "predictable")   |> mutate(source = "Decomposed")
  ) |>
    pivot_wider(id_cols = model, names_from = source, values_from = estimate)

  undecomposed <- interest_rate_diff_models |> 
    pluck(2) |> 
    pretty_table(surprise_exist = 0, label = "Undecomposed") |>
    pivot_wider(id_cols = model, names_from = source, values_from = estimate)

  bind_rows(sa_news, sa_resids, main, undecomposed) |>
    mutate(
      group_var = if_else(str_detect(model, "spot"),  "Spot",
                  if_else(str_detect(model, "2y"),    "2-year Rates",
                  if_else(str_detect(model, "5y"),    "5-year Rates",
                  if_else(str_detect(model, "10y"),   "10-year Rates", "Other"))))
    ) |>
    relocate(group_var, .after = model) |>
    group_by(group_var) |> 
    arrange(model, .by_group = TRUE) |> 
    as_grouped_data(groups = "group_var") |> 
    flextable()
}

```



```{r}

tables <- 
  c("target_models", "forward_guidance_models", "central_bank_information_models", "country_risk_models") |>
  set_names() |> 
  map(~combined_table(.x))

tables[[1]] 
  
```



```{r}
tables[[2]] 
```



```{r}
tables[[3]]
```



```{r}
tables[[4]]
```


# Conclusion

\newpage 
# References {.unnumbered}
::: {#refs}
:::


\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}

\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}

\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}

\newpage

# Appendix

## Data


```{r}
#| label: latex_version
#| warning: FALSE
#| message: FALSE

# Packages -----------------------------------------------------------
library(here)
library(tidyverse)
library(fs)


# Delete current latex folder ----------------------------------------
if (dir.exists(here("Latex_version"))) {
  dir_delete(here("Latex_version"))
}

# Create folder ------------------------------------------------------
dir.create(here("Latex_version"), recursive = TRUE)

# Copy text files ---------------------------------------------------------
list.files(path = ".", pattern = "tex", full.names = TRUE ) %>%
  file.copy(to = here("Latex_version"), overwrite = TRUE)
file.copy(here("references.bib"), here("Latex_version"), overwrite = TRUE)

# Copy resources folder ---------------------------------------------
folder_path <- list.dirs(path = ".", recursive = FALSE) %>%
  str_subset("files")
folder_name <- str_remove(folder_path, "./")
dir_copy(folder_path, here("Latex_version", folder_name), overwrite = TRUE)

```
